---
title: "Lecture 7 Homework Framework"
format: 
  html:
    self-contained: true
---

```{r setup, include=FALSE}
#| warning: false
library(tidyverse)     # loads the tidyverse tools
library(RPostgres)     # loads the database driver for PostgreSQL
library(connections)   # helps RPostgres work with RStudio
library(keyring)       # access to a local encrypted keychain for passwords


con <- connection_open(RPostgres::Postgres(),
          dbname = "syntheticMGUH",
          host = "35.199.4.72",
          user = "hids502_student",
          password = key_get(service = "syntheticmguh", 
                             username = "hids502_student"),
          # Tell the driver to return very large integers as floating point (vs truncating them)
          bigint = "numeric")

```

# SyntheticMGUH Registry

A clinician has collected a series of patients that they will to work with other researchers on. This collection was derived from an EMR and is present in the SyntheticMGUH database as a table called `inpatientregistry` (technically a view). 

* [NIH PHI Review](https://privacyruleandresearch.nih.gov/pr_08.asp#8a) - Includes the 18 elements

They have placed their registry in your regulard database in a table called `inpatientregistry`. Note that it contains columns that are identifiers, and columns that are not. *Your homework report should not contain any identifiers. You will be docked points if it does.*

```{sql connection=con}
-- Note that you should delete this section, its just an example
SELECT * FROM inpatientregistry LIMIT 5
```

# Fully De-identified Table

Create and return a data set that is fully de-identified.

 * Include all dates 'date shifted'
 * Include the age at the time of admission and age at the date of death (from the original dates)
 * Include as much of the data as possible, without violating HIPAA!

Build a patient lookup table. Note that we should probably randomize the order of the MRNs to make sure that our new ones and the old ones aren't in synch. This happens naturally here, but normally it would be best practice.

```{sql connection=con}
-- Example code to demonstrate the use of the functions that we will need!

-- Assume July 1st 2023 is an admission, July 7th is a discharge and Jan 1, 1945 is a birthday
SELECT MD5('Nathan Cobb'), -- MD5 hash,
CAST(67956541/1000000 AS INT), -- a psuedo random number
CAST(RANDOM()*100 AS INT) random_integer, -- a real random numbers
CAST('1945-01-01' AS DATE) + CAST(RANDOM()*100 AS INT) date_with_offset, -- Add 1 day to a date
CAST('2023-07-07' AS DATE) - CAST('2023-07-01' AS DATE) , -- Difference in days between dates
AGE(CAST('2023-07-01' AS DATE), CAST('1945-01-01' AS DATE)), -- Age -- but not in years!!!
DATE_PART('YEAR', CAST('2023-07-01' AS DATE)), -- Extracting the year from a date
DATE_PART('YEAR', AGE(CAST('2023-07-01' AS DATE), CAST('1945-01-01' AS DATE))) -- Or from an age
```

```{sql connection=con}
-- Constructing a CTE lookup table to create random numbers for each patients.
-- You will need to join back against this to add the numbers to create a date shift.
WITH date_shifts_lookup AS (
  SELECT medical_record_id, 
  CAST(RANDOM() * 100 AS INT) random_date_offset -- We want an integer number of days
  FROM inpatientregistry
  )
SELECT * from date_shifts_lookup
```

```{sql connection=con}
-- Constructing a CTE lookup table to create random numbers for each patients.
-- You will need to join back against this to add the numbers to create a date shift.
WITH mrn_lookup AS (
  SELECT medical_record_id, 
  row_number() OVER (ORDER BY medical_record_id) AS new_medical_record_id
  FROM inpatientregistry
  )
SELECT * from mrn_lookup
```
# Limited Data Set Table

Create and return a data set that is de-identified to HIPAA standards. Technically you can return a date of birth, but generally there is no good reason to do so (unless its a pediatric patient).

# Demonstrate Equivilence

Show that the 3 tables are equivilent, that we have not lost or corrupted any data in the process. At the minumum, show that you have the same number of unique identifiers (in other words, your deidentified results have the exact same number of patients as the original table.)
